language: java
jdk:
  - oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  - secure: aHymzi4IVCeX5lZA9j3ovJXZ9UW3YHczVZQuYahkqXiycOanCF8ZxHwWgYjt/tQnhxgabll4Lz/ZkBFf4z7WyxfA1I7UQ3BIIj0RmONzK1XZGLagLHovBb0f6sMOVYHqjHoZ9GgwomIyDYJoDIsV2cd040vBctSHPe8SpIxcefo=
  - secure: FqGggOGREA4csW+xPNtC1zwX543FJ0oGz78fHVxD2eRAKqDTwfAmEg60633laXBxn79/oN/MTm5f4+iad9hntNqgILqy4YN9OX79t22FqXRy7yEOu+0WBNszjYR4zMRed1nGX226RlTAYZ2g8UUR3b+a62B4BWX/ci6X7EsNUoc=
  - secure: ObS+5VJqk+K/3Ln3j47XVEt/KHTv+a44B3gUD2tl7PsLfptF7ExikcCRQ4Gpv40dNuy+4cJydbxmXxfxv5WI6JmhDcIT5YDh9Mmkxl0+lL5KmJSNnIQY40gUjSrwKtCPy97Lc9brTkL9RtcPQwyUJTkpXfOfF2cEjEfqb74fVPA=

install: "./gradlew --version"

script: ./gradlew build test aggregateJavadoc publishGhPages -PgithubUser="${GITHUB_TOKEN}" -PgithubPassword="" -PjfrogUser="${jfrogUser}" -PjfrogPassword="${jfrogPassword}"

